<?php
  Page::registerGoogleCharts();
  Page::registerChart('displaysByYear');
?>
          <p>In 2005, <abbr title="Case Western Reserve University">CWRU</abbr> opened 8 new residence halls and each building had an <abbr title="Liquid Crystal Display">LCD</abbr> info board in the lobby. A year later, the system was already showing its age. The consumer-grade <abbr title="televisions">TVs</abbr> had developed permanent image retention from the mostly-static images. The attached computers had to be set to reboot each night because the software was unstable.</p>
          <p>As a student employee in the summer of 2006, I was asked to look at options to improve or replace the existing system.</p>
          <p>My initial research suggested that the software was not a good fit for our use case. My supervisor agreed with my conclusions and I got to work on a custom solution. I focused on consuming existing data sources, starting with simple <abbr title="Rich Site Summary, RDF Site Summary, or Really Simple Syndication">RSS</abbr> and <abbr title="iCalendar">iCal</abbr> feeds. I went on to screen-scrape laundry machine statuses and shuttle bus arrival predictions. The most exotic integration was polling public printer statuses via <abbr title="Simple Network Management Protocol">SNMP</abbr>. I went on to deliver 4 major versions of the software as I rose from student employee to Application Developer.</p>
          <p>Administrators liked my software enough that they invested in adding displays across campus. The graph below shows its growth from an 8-display pilot to 36 installations and 2 campus <abbr title="television">TV</abbr> stations. For most of those, I handled everything from writing the proposals to overseeing the installations. Switching to 24x7-rated <abbr title="Liquid Crystal Display">LCD</abbr> panels and varying the screen layout reduce image retention.</p>
          <div id="chart_displaysByYear" style="height: 400px;"></div>
