<?php
  Page::registerGoogleCharts();
  Page::registerChart('physicalAccessPerYear');
?>
          <h3>Responsibilities</h3>
          <ul>
            <li></li>
          </ul>
          <hr/>
          <h3>Summary</h3>
          <p></p>
          <div id="chart_physicalAccessPerYear" style="width: 100%; height: 400px;"></div>
          <hr/>
          <h3>Highlights</h3>
          <p></p>
          <ul>
            <li>
              <h4></h4>
              <p></p>
            </li>
          </ul>
